# Generated by Django 4.2.6 on 2023-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Suffolk Coins Inventory Item', max_length=100)),
                ('file', models.FileField(default='inventory_files/blank.pdf', upload_to='inventory_files')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
